print("S")
print("e")
print("b")
print("a")
print("s")
print("t")
print("i")
print("a")
print("n")
print("")
print("Ö")
print("h")
print("m")
print("a")
print("n")

# print("S\ne\nb\na\ns\nt\ni\na\nn\n \nÖ\nh\nm\na\nn")

# print("\n".join(list(("Sebastian Öhman"))))